name: MyTestWorkFlow
# GIT Trigger evvent(s): [push, pull_request, etc..]
on: [push]
#jobs and sequence steps to run on event
jobs:
  # silly name for job
  say-hello: 
    # hub.docker container
    runs-on: ubuntu-latest
    steps: 
      -  run: echo "Hello, GitHub Action for ubuntu-latest starts here..."

  # next job to build C code
  build-and-test:
    # set dependencies
    needs: [say-hello]
    runs-on: ubuntu-latest
    steps:
      # uses boilerplate action code - get it from github first
      - name: Check out boilerplate repo
        uses: actions/checkout@v3

      # install required packaes
      - name: Install dependencies on ubuntu-latest instance
        run: sudo apt install -y build-essentials python3
 
      # sanity check
      - run: pwd

      # run tests
      - name: Run test 1
        run: python3 test.py


